config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users
 
  root 'index#index'

  resources :favorite_opportunities, only: [:create, :destroy]


  get '/about', to: 'index#about'

  get '/causes/:cause', to: 'causes#show', as: 'cause'
  get '/opportunities/', to: 'opportunities#index', as: 'opportunities'
  get '/opportunities/new', to: 'opportunities#new' , as:'newopp'
  get  '/opportunities/:id', to: 'opportunities#show', as: 'opportunity'
  get '/users/:user_id', to: 'users#show', as: 'user'
  get '/organizations/', to: 'organizations#index', as: 'orgs'
  get '/organizations/new', to: 'organizations#new' , as: 'neworg'
  get '/organizations/:id', to: 'organizations#show', as: 'org'
  post '/opportunities/:id/useropp', to: 'useropp#create', as: 'create_user_opp'
  post '/opportunities', to: 'opportunities#create'
  post '/organizations', to: 'organizations#create'
  delete '/opportunities/:id', to: 'opportunities#destroy', as: 'destroy_opp'
  delete '/organizations/:id', to: 'organizations#destroy', as: 'destroy_org'
 

  # route to redirect users to root if they enter invalid URL
  match '*path', to: 'index#index', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/opportunity.rb
class Opportunity < ApplicationRecord
	has_many :users, through: :useropps
	has_many :useropps, dependent: :destroy
	belongs_to :organization, optional: true
end

app/models/organization.rb
class Organization < ApplicationRecord
	has_many :opportunities
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
	has_many :useropps, dependent: :destroy
	has_many :opportunities, through: :useropps

	has_many :favorites
  	has_many :favorite_opportunities, through: :favorites, source: :favorited, source_type: 'Opportunity'
end

app/models/useropp.rb
class Useropp < ApplicationRecord
  belongs_to :opportunity
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    # to allow custom fields to save on devise database
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :location]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/causes_controller.rb
class CausesController < ApplicationController
  
  def index
  	render "index"
  end
   
  def show
    cause_type = params[:cause]
    cause_type.gsub! '%20', ' '
    # find all opportunities for that cause
    @opportunities = Opportunity.where(cause: cause_type)
    # @opportunities = Opportunity.where("cause ILIKE 'ENVIRONMENT'")
  end

end

app/controllers/favorite_opportunities_controller.rb
class FavoriteOpportunitiesController < ApplicationController
  before_action :set_opportunity
  
  def create
    if Favorite.create(favorited: @opportunity, user: current_user)
      redirect_to @opportunity, notice: ' has been favorited'
    else
      redirect_to @opportunity, alert: 'Something went wrong...*sad panda*'
    end
  end
  
  def destroy
    Favorite.where(favorited_id: @opportunity.id, user_id: current_user.id).first.destroy
    redirect_to @opportunity, notice: 'This opportunity is no longer in favorites'
  end
  
  private
  
  def set_opportunity
    @opportunity = Opportunity.find(params[:opportunity_id] || params[:id])
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
  	@opportunities = Opportunity.all

  end

  def about
    
  end
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
	def index
    @opportunities = Opportunity.all
  end

  def show
    set_opp
  end

  def new
    @opportunity = Opportunity.new
  end
  
  def create
    @opportunity = Opportunity.create(opportunity_params)
    redirect_to opportunities_path
    end
  

    def destroy 
     set_opp  
     @opportunity.destroy
     respond_to do |format|
      format.html { redirect_to opportunities_path, notice: 'Opportunity was successfully destroyed.' }
      format.json { head :no_content }
    end
   end

private

  def set_opp
    @opportunity = Opportunity.find(params[:id])
   end

def set_user
    @user = User.find(params[:user_id])
  end

def opportunity_params
  params.require(:opportunity).permit(:name, :location, :cause)
end
 end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

def index
 	@organizations = Organization.all
end

def new
    @organization = Organization.new
  end
   
def show  
	set_org
end

  def create
    @organization = Organization.create(organization_params)
    redirect_to organizations_path
 end


 def destroy 
     set_org  
     @organization.destroy
     respond_to do |format|
      format.html { redirect_to opportunities_path, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
   end

private

def set_org
   @organization = Organization.find(params[:id])
end
  

def set_user
  @user = User.find(params[:user_id])
end
 
def organization_params   
    params.require(:organization).permit(:name, :location, :mission_statement, :description, :website)
  end
end

app/controllers/useropp_controller.rb
class UseroppController < ApplicationController
  before_action :require_ownership
  before_action :authenticate_user!

 
 

  # prevents users from creating, editing, deleting a tip that wasn't created by them
  def require_ownership
    if current_user.nil?
      redirect_to root_path
      flash[:notice] = "Sorry, you don't have access to this function"
    elsif current_user.username != params[:user_id]
      redirect_to user_path(current_user)
      flash[:notice] = "Sorry, you don't have access to this function"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  

  #get '/users/', to: 'users#index', as: 'users'
  def index
    @users = User.all

  end

  #get '/users/:user_id', to: 'users#show', as: 'user'
  def show
    set_user
    @opportunities = @user.opportunities
    @opp = @user.favorite_opportunities
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def user_params
    params.require(:user).permit(:username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/causes/show.html.erb
<%= render ('/layouts/largenavbar') %>
<br><br><br> <br><br><br> 

<div class="container">        
            <% @opportunities.each do |opportunity| %>
              <div class="col-sm-8 col-sm-offset-2 causebox" style= "border:0px solid #ccc;">
               <%= link_to opportunity.cause %>
              </div> 
               <% break %>       
            <% end %>
        </div>

  <div class="col-sm-12">

      <br><br><br>    
     
        <div class="container">        
            <% @opportunities.each do |opportunity| %>
              <div class="col-sm-8 col-sm-offset-2 causebox" style= "border:10px solid #ccc;background-color: #fcf8e3;">
                
               <%= link_to opportunity.name, opportunity_path(opportunity.id) %>
               <br><br><br>
               <%= opportunity.location%>                           
                 <% opportunity.created_at.strftime("%a, %b %d, %Y @ %l:%M %p %Z") %>
                  
              </div>        
            <% end %>
        </div>
   
  </div>

      

app/views/index/index.html.erb
<%= render ('/layouts/largenavbar') %>

<div class="container-fluid user-true">
  <div class="row justify-content-center">
    <div class="col-sm-12 align-self-center banner-padding">
      <div class="banner">
        <h5> Uncover the causes we support and the opportunities available to volunteers who are interested in participating in these event</h5>
      </div>
    </div>
    <div class= "col-lg-12">
    <div class= "row">
    <div class="col-sm-4 align-self-center">
      <%= link_to '/causes/Human Rights & Advocacy' do %>
      <%=  image_tag 'candy2.jpg', :class => "border-pic", :style => "margin-top: 24px;" %>
      <% end %>
      <div class="text">Human Rights & Advocacy</div>
    </div>
    <div class="col-sm-4 align-self-center">
      <%= link_to '/causes/Children & Youth' do %>
      <%=  image_tag 'candy1.jpg', :class => "border-pic"  %>
      <% end %>
      <div class="text">Children & Youth</div>
    </div>
    <div class="col-sm-4 align-self-center">
      <%= link_to '/causes/Homeless & Housing' do %>
      <%=  image_tag 'handh1.jpg', :class => "border-pic"  %>
      <% end %>
      <div class="text">Homeless & Housing</div>
    </div>
    <div class="col-sm-4 align-self-center">      
      <div class="col-sm-4 align-self-center">
            <%= link_to '/causes/Environment' do %>
            <%=  image_tag 'enviro3.jpg', :class => "border-pic",:style => "margin-left: -15px;" %>
            <% end %>            
      <div class="text">Environment</div>
    </div>   
  </div>
</div>
</div>
</div>







          

    

app/views/layouts/_largenavbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
   <!-- Brand and toggle get grouped for better mobile display -->
   <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a href="/">
         <p class="LEND"> LEND A <span class= "glyphicon glyphicon-hand-right" ></span> HAND</p>
      </a>
   </div>
   <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
         <li>
            <a href="/opportunities">Opportunities</a>
         </li>
         <li>
            <a href="/organizations">Organizations</a>
         </li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Causes<b class="caret"></b></a>
            <ul class="dropdown-menu">
               <li>
                  <a href="/causes/Human Rights & Advocacy">Human Rights & Advocacy</a>
               </li>
               <li>
                  <a href="/causes/Children & Youth">Children & Youth</a>
               </li>
               <li>
                  <a href="/causes/Homeless & Housing">Homeless & Housing</a>
               </li>
               <li>
                  <a href="/causes/Environment">Environment</a>
               </li>
            </ul>
         </li>
         <li class="dropdown1">
            <span></span>
            <% flash.each do |name, msg| %>
            <%= msg %>
            <% end %>
            <div class="pull-right">
               <% if signed_in? %>
               <span>
               Welcome, <%= link_to current_user.first_name, user_path(current_user) %>
               <%= link_to edit_user_registration_path(current_user) do %>
               <span class="glyphicon glyphicon-cog"></span>
               <% end %>
               <%= button_to "Sign Out", destroy_user_session_path, :method => :delete, class: "signout" %>
               </span>
               <% else %>
               <div class="sign_in"></div>
               <%= button_to "Sign In", new_user_session_path, class: "signin" %> 
               <%= button_to "Sign Up", new_user_registration_path, :method => :get, class: "signup" %>
               <% end %> 
         </li>
      </ul>
      </div>
      <!-- /.navbar-collapse -->
   </div>
   <!-- /.container -->
</nav>

app/views/layouts/_sidenavbar.html.erb
<header>
  <div class="jumbotron-small navbar-fixed-top">
    <div class="logo-left">
      <a href="/"><p class="LEND">LENDA <span class="glyphicon glyphicon-hand-right"></span>HAND</p></a> 
    </div>
    <span class= "flash_message">
    <% flash.each do |name, msg| %>
        <%= msg %>
      <% end %>
    </span>
    <div class="pull-right dropdown">
      <% if signed_in? %>
        <div class="dropbtn">
          Welcome, <%= current_user.first_name%>
          <%= image_tag("dropdown.png", height: "30") %>
        </div>
        <div class="dropdown-content">
          <%= link_to "View Profile", user_path(current_user) %>
          <%= link_to "Settings", edit_user_registration_path(current_user) %>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
        </div>
      <% else %>
        <%= button_to "Sign In", new_user_session_path %>
        <%= button_to "Sign Up", new_user_registration_path, :method => :get %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VolunteerApp</title>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  	<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>

   
    <%= yield %>
  </body>
</html>

app/views/opportunities/index.html.erb
<%= render ('/layouts/largenavbar') %>

<br><br><br>
     <h1>&#160;&#160;&#160;&#160;Current Opportunities</h1>

<div class="container">
	<div class="row justify-content-center">
		<div class="col-sm-8">

<% @opportunities.each do |opportunity| %>

	<%= link_to opportunity_path(opportunity) do %>        
    <%= opportunity.name %> 
    <br>
    <%= opportunity.location %>
<%end%>
<%end%>
</div>
</div>
<br>
<br><br>

<button type="button" class="btn "><%= link_to "Add New Opp", newopp_path, class: "Add New" %> </button>



</div>

app/views/opportunities/new.html.erb
<%= form_for @opportunity do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.text_field :location, placeholder: "location" %>
  </div> 
  <div>
    <%= f.text_field :cause, placeholder: "cause" %>
  </div>

<%console %>
  <%= f.submit %>
<% end %>

app/views/opportunities/show.html.erb
<%= render ('/layouts/largenavbar') %>

<br><br><br>

   
       <div class="row">
           <div class="col-sm-8">
                <h4><%= @opportunity.name%></h4>
                <ul>
                  <li>Location : <%= @opportunity.location%></li>
                  <li>Cause : <%= @opportunity.cause%></li>
                  <li>Organization : <%= @opportunity.organization.name%></li>
                </ul>
                   

                  
                <div class= "favorites"> 
                <% if signed_in? %>
                <% unless current_user.favorite_opportunities.exists?(id: @opportunity.id) %>
				<%= link_to 'Add to favorites', favorite_opportunities_path(opportunity_id: @opportunity), method: :post %>
				<% else  %>
				<%= link_to 'Remove from favorites', favorite_opportunity_path(@opportunity), method: :delete %>
				<% end %>
				<% end %>
				</div>
        <button type="button" class="btn "><%= link_to "Delete Opp", destroy_opp_path(@opportunity), method: :delete%> </button>
				
        

            </div>
        </div>
   
   <%= console %>

app/views/organizations/index.html.erb
<%= render ('/layouts/largenavbar') %>

<br><br><br>

<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-7">

<% @organizations.each do |organization| %>

	<%= link_to org_path(organization) do %> 

    <%= organization.name %> 
  
    <%= organization.location %>
   
    <%= organization.website %>


<%end%>
<%end%>

 <%= link_to "Add New Org", neworg_path, class: "Add New" %>


       </div>
    </div>
</div>

app/views/organizations/new.html.erb
<%= form_for @organization do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.text_field :location, placeholder: "location" %>
  </div>
  <div>
    <%= f.text_field :mission_statement, placeholder: "mission_statement" %>
  </div>
  <div>
    <%= f.text_field :description, placeholder: "description" %>
  </div>
  <div>
    <%= f.text_field :website, placeholder: "website" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/organizations/show.html.erb
<%= render ('/layouts/largenavbar') %>
  
  <br><br><br>
    <div class="row">
        <div class="col-sm-8">
            <p><%= @organization.name %></hp> 
            <p> <%=@organization.location %></p>
            <p> <%=@organization.mission_statement %></p>
            <p> <%=@organization.description %></p>
            <p><%= @organization.website %></p>       
        </div>    
    	<div>
        	<%= link_to "Delete Org", destroy_org_path(@organization), method: :delete%>
        </div>
    </div>
                   
               
        

app/views/users/index.html.erb
<%= render ('/layouts/navbar') %>

<h1>hi</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.email, user_path(user)%></li>
   >
  <% end %>
</ul>

app/views/users/show.html.erb
<%=render ('/layouts/largenavbar') %>

 <div class="container-fluid">
   <div class="row profile-user">
     <div class="col-sm-3 col-md-3 col-lg-3">
       <div class="profile-sidebar nav-stacked affix" id="sidebar">        
    		<div class="col-sm-9 col-md-9 col-lg-9">
       		<% @opportunities.each do |opportunity| %>
         <div class="container-fluid tips">
           <div class="row">
             <div class="col-sm-12 col-md-12 col-lg-12">
               <div class="usertip-title">
                <h3>
                  <%= opportunity.name %>
                </h3>
                 <div class="container-fluid content">
                   <div class="col-sm-8">
                    <div class="pull-left">
                      <%= opportunity.cause %>
                     </div>
                   </div>
                   </div>
                 </div>

                 <div class="pull-left">

                  <%= link_to opportunity.cause, opportunity_path(opportunity.cause) %>
                 
                   <%= opportunity.created_at.strftime("%a, %b %d, %Y @ %l:%M %p") %>

                  <div class="pull-right">
                     <% @opp.each do |fav| %>
                      <div class="">
                     <%= link_to fav.name, fav %>
                    </div>
                <% end %>
                 	</div>           
               </div>
             </div>
          </div>        
      <% end %>
      </div>
    </div>
    </div>
  </div>
</div>